site_name: Quant ML Intraday
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Inicio: index.md
  - Metodología: methodology.md
  - Arquitectura: architecture.md
  - Resultados Recientes: results.md
  - Notas de investigación: research_notes.md
  - Gestión de Riesgo: risk_management.md
