name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Lint (Ruff)
        run: poetry run ruff check .

      - name: Type check (Mypy)
        run: poetry run mypy src

      - name: Run tests (pytest)
        run: poetry run pytest --cov=src --disable-warnings
